// import './instance'
// import './lifecycle'
// import './data-binging'
// import './computed'
// import './directive'
// import './components'
// import './components/extend'
// import './components/v-model'
// import './components/features'
import './components/render'
